### ISSUE TITLE
Install test error

### ISSUE THREAD

**Issue by kk17** [igorbolic/memcached-spring-boot#2]
```
memcached-spring-boot git:(master) gradle clean test install
:memcached-spring-boot-autoconfigure:clean
:memcached-spring-boot-starter:clean UP-TO-DATE
:memcached-spring-boot-autoconfigure:processResources
:memcached-spring-boot-autoconfigure:compileJava
:memcached-spring-boot-autoconfigure:classes
:memcached-spring-boot-autoconfigure:compileTestJava
:memcached-spring-boot-autoconfigure:processTestResources NO-SOURCE
:memcached-spring-boot-autoconfigure:testClasses
:memcached-spring-boot-autoconfigure:test

rs.symbolic.memcached.cache.MemcachedAutoConfigurationTest > thatMemcachedWithMissingConfigurationValuesIsLoaded FAILED
    java.lang.AssertionError at MemcachedAutoConfigurationTest.java:147

rs.symbolic.memcached.cache.MemcachedAutoConfigurationTest > thatMemcachedWithCustomConfigurationIsLoaded FAILED
    java.lang.AssertionError at MemcachedAutoConfigurationTest.java:147

22 tests completed, 2 failed
:memcached-spring-boot-autoconfigure:test FAILED
```

**Comment by igorbolic** [comment]
Could you please run it with gradle `--info` option: `gradle clean test --info` and send me the output of the failed tests.

**Comment by kk17** [comment]
```
rs.symbolic.memcached.cache.MemcachedAutoConfigurationTest > thatMemcachedWithMissingConfigurationValuesIsLoaded FAILED
    java.lang.AssertionError: Memcached node endpoint host is incorrect
    Expected: is "192.168.99.100"
         but: was "dockerhost"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at rs.symbolic.memcached.cache.MemcachedAutoConfigurationTest.assertMemcachedClient(MemcachedAutoConfigurationTest.java:147)
        at rs.symbolic.memcached.cache.MemcachedAutoConfigurationTest.thatMemcachedWithMissingConfigurationValuesIsLoaded(MemcachedAutoConfigurationTest.java:135)
```
In my `/etc/hosts` file,  domain `dockerhost` is seted to ip `192.168.99.100`, which cause this problem. Without this host setting, tests are ok.

**Comment by igorbolic** [comment]
Thank you for the further info. 
I've pushed a fix for test cases. Let me know if your build is successful now.

**Comment by kk17** [comment]
Great! My build is successful now.
