### ISSUE TITLE
Lombok compile issue with Java 9

### ISSUE THREAD

**Issue by igorbolic** [igorbolic/memcached-spring-boot#7]
When building project with **Java 9 (build 9+181)**, compile stage is failing with the following error:

`ConditionalOnMissingSpringCacheType.java:33: warning: lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation: java.lang.IllegalArgumentException: com.sun.tools.javac.api.ClientCodeWrapper$WrappedStandardJavaFileManager extends com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager implements javax.tools.StandardJavaFileManager
@interface ConditionalOnMissingSpringCacheType {
 ^
        at lombok.javac.apt.LombokFileObjects.getCompiler(LombokFileObjects.java:130)
        at lombok.javac.apt.InterceptingJavaFileManager.<init>(InterceptingJavaFileManager.java:40)
        at lombok.javac.apt.LombokProcessor.placePostCompileAndDontMakeForceRoundDummiesHook(LombokProcessor.java:164)
        at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:85)
        at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
        at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:140)
        at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:69)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:675)`

For the time being we should remove the Lombok dependency from the project, until this issue has been fixed ([Issue 985](https://github.com/rzwitserloot/lombok/issues/985))

**Comment by igorbolic** [comment]
Thanx @sasabolic
